name: client
description: "Свежие продукты с доставкой"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.0.0
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  http: ^1.1.0
  flutter_native_splash: ^2.4.7
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5
  drift: ^2.29.0
  drift_flutter: ^0.2.7
  sqlite3_flutter_libs: ^0.5.0
  injectable: ^2.6.0
  get_it: ^9.0.5
  path_provider: ^2.1.5
  dartz: ^0.10.1

  connectivity_plus: ^4.0.2
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.29.0
  injectable_generator: ^2.9.1
  build_runner: ^2.10.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/transparent.png

flutter_native_splash:
  color: "#000000"
  image: "assets/images/transparent.png"
  android: true
  ios: true
  web: true
  android_12:
    color: "#000000"
    image: "assets/images/transparent.png"